### ISSUE TITLE
Swagger

### ISSUE THREAD

**Issue by qcjxberin** [topnguyen/Elect#1]
How Swagger components are set to require verification of tokens.

**Comment by topnguyen** [comment]
Hi @qcjxberin 
So sorry for late response.

For my swagger option have property [ExtendOptions](https://github.com/topnguyen/Elect/blob/master/src/Web/Elect.Web.Swagger/Models/ElectSwaggerOptions.cs#L111) allow you can add adjust `SwaggerGenOptions` after my middleware finish config it.

- Then use can add as code below to add more header and require it for each http request
```c#
services.AddElectSwagger(x => {
 x.ExtendOptions = (options) => {
        options.AddSecurityDefinition("Bearer", new ApiKeyScheme { In = "header", Description = "Please enter JWT with Bearer into field", Name = "Authorization", Type = "apiKey" });
        options.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>> {
                { "Bearer", Enumerable.Empty<string>() 
        };
    };
});
```

- If you only use the Bearer token and it will be optional for http request, it's implement already in my middleware.
- Please follow and run [my sample](https://github.com/topnguyen/Elect/tree/master/samples/Web/Elect.Sample.Web.Swagger) then you will see the "Auth Token" in the left menu. I append "Bearer " as default so you just give the JWT token, blur/out focus the input and try to API.

Hope this is useful for you.
