### ISSUE TITLE
Không thể lấy được giờ coordinated universal time 

### ISSUE THREAD

**Issue by datttit** [topnguyen/Elect#3]
Chào anh top
Em có tham khảo elect về việc sử dụng packet TzConverter để fix lỗi về time zone khi deploy trên linux .
Sau khi deploy thì em phát hiện trong log file có excepition . Báo rằng ko tìm thấy time zone coordinated universal time :D . (funny)
Anh có thể copy "Coordinated Universal Time" để test method DateTimeHelper.GetTimeZoneInfo("Coordinated Universal Time") . 
Em hiện tại hard code if else thôi chưa có ý tưởng để fix , có lẽ bảo thằng viết TzConverter nó fix. :D 
Nó chính là giờ UTC múi giờ +0.00 :D . Buồn cười haha
Thank anh .

**Comment by topnguyen** [comment]
Hello babe, 

Cảm ơn babe đã dùng Elect nha, phần Date Time Timezone này babe dùng "Coordinated Universal Time" có vẻ sai sai rồi.

Babe vào đây nè https://github.com/topnguyen/Elect/blob/master/src/Elect.Core/DateTimeUtils/DateTimeHelper.cs#L103

Mình có note là dùng Time zone name từ danh sách của Microsoft nha, link này https://docs.microsoft.com/en-us/previous-versions/windows/embedded/gg154758(v=winembedded.80)

Trong list timezone name từ Microsoft, không có "Coordinated Universal Time" nhé.
Babe muốn lấy UTC thì dùng "UTC" luôn nhé.

Hiện tại mặc định các lib khác của Elect như Elect.DataTable cũng đang setup mặc định là UTC timezone và vẫn work well nên babe check lại giúp mình nhe.
