### ISSUE TITLE
Duplicate Profile

### ISSUE THREAD

**Issue by rollback228** [topnguyen/Elect#5]
Gửi bạn,
Mình có sử dụng Elect AutoMapper nhưng khi khai báo xong toàn bị báo :
AutoMapper.DuplicateTypeMapConfigurationException
  HResult=0x80131500
  Message=The following type maps were found in multiple profiles:

Khi mình kiểm tra lại các profile thì ko bị trùng. Vậy hi vọng có thể nhờ bạn support mình. Cảm ơn

**Comment by topnguyen** [comment]
Hi Bạn,

Trong lib của mình có call validation chính chủ của Auto Mapper ([xem chi tiết](https://github.com/topnguyen/Elect/blob/69aaca7aa8f4d92f438cf408a17f9aeb1db42b79/src/Mapper/Elect.Mapper.AutoMapper/IServiceCollectionExtensions.cs#L166)) để validate xem profile config đúng hay bị trùng không.

Bạn thử kiểm tra lại kỷ xem các profile có bị trùng giữa các profile trong các projects có cùng namespace không do mình dựa trên namespace của project mà scan các Profile hiện có ([xem chi tiết](https://github.com/topnguyen/Elect/blob/69aaca7aa8f4d92f438cf408a17f9aeb1db42b79/src/Mapper/Elect.Mapper.AutoMapper/IServiceCollectionExtensions.cs#L86)).

Nếu sau khi check kỷ bạn vẫn bị lỗi, nếu được vui lòng gửi mình source code và miêu tả để mình check thử.

Chúc bạn Happy Coding.

**Comment by topnguyen** [comment]
Mình close issue này do bạn get lại source code, build lại và issue không bị nữa!
