### ISSUE TITLE
Get method doesn't exclude soft deleted related entities

### ISSUE THREAD

**Issue by daltonnyx** [topnguyen/Elect#6]
Try to use ```Get()``` method to get a list of entities that insides of each object contains a list of other entities which contains any soft deleted object. 

The soft deleted still show up.

**Comment by topnguyen** [comment]
Hi Quý,

Could you give more information about the type of `Repository` and type of `Entity` you have inherited from Elect Lib?

**Comment by topnguyen** [comment]
Hi Quý,

The `Get` method just add a `Where` clause for the linq.
So it mean just filter for the object, not related/child objects.

If you would like to have filter all Deleted Record, you would use Global Filter feature of EF Core.

Please refer to Global Delete Filter - `SetSoftDeleteFilter()` method via https://github.com/topnguyen/Elect/blob/5b4ef03dc42a2a6337ffcb2b26a27a994805e608/src/Data/Elect.Data.EF/Utils/ModelBuilderUtils/ModelBuilderExtensions.cs#L200

Use the above extension method in your `DbContext` class inside `OnModelCreating` method.

**Comment by daltonnyx** [comment]
Hi Top,

 The Repositories is derived from ```Elect.Data.EF.Services.Repository.BaseEntityRepository<T>``` and the Entities is derived from ```Elect.Data.EF.Models.BaseEntity``` and implements ``` ISoftDeletableEntity``` interface.

Here is the derived entity class:
```
    public abstract class Entity : BaseEntity, ISoftDeletableEntity, IAuditableEntity
    {
        protected Entity()
        {
            CreatedTime = LastUpdatedTime = Building3DDateTimeHelper.UtcTimeNow;
        }

        public long Id { get; set; }

        public long? CreatedBy { get; set; }

        public long? LastUpdatedBy { get; set; }

        public long? DeletedBy { get; set; }
    }
```

**Comment by daltonnyx** [comment]
Oh. Thank for your instructions. Let me try it out

**Comment by topnguyen** [comment]
I close this issue due to long time not response from @daltonnyx 
Feel free to reopen it if you still face the issue
